# Generated by Django 5.2.1 on 2025-05-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirements',
            unique_together={('school_class', 'teacher_subject')},
        ),
    ]
