# Generated by Django 5.2.1 on 2025-05-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_alter_requirements_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
